version: 2.1

############################################################################
orbs:
  aws-s3: circleci/aws-s3@3.0.0
  jq: circleci/jq@2.2.0

############################################################################

attach-workspace: &attach-workspace
  attach_workspace:
    at: ~/

store-artifacts: &store-artifacts
  store_artifacts:
    path: build/dist

persist-workspace: &persist-workspace
  persist_to_workspace:
    root: ~/
    paths:
      - repo

persist-artifacts: &persist-artifacts
  persist_to_workspace:
    root: ~/
    paths:
      - repo/build/dist

############################################################################

commands:
  package-builder:
    steps:
      - *attach-workspace
      - jq/install
      - run:
          name: Build with package builder
          command: |
            PKG_VERSION=$(jq -r '.version' package.json)
            PKG_NAME=$(jq -r '.name' package.json)
            PKG_DESC=$(jq -r '.description' package.json)
            make WORKSPACE="~/repo/pkg" VERSION=$PKG_VERSION NAME=$PKG_NAME DESC="$PKG_DESC"
      - *store-artifacts
      - *persist-artifacts


################# Jobs #########################

jobs:
  prepare-npm-deps:
    executor: default-executor

    steps:
      - checkout

      # Download cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            # fallback to using the cache from the same branch
            - v1-dependencies-{{ .Branch }}-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # install dependencies
      - run: npm install --no-audit

      - run:
          name: Checking out dependencies
          command: git clone https://github.com/Zimbra/zm-pkg-tool.git ~/zm-pkg-tool

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths:
            - repo
            - zm-pkg-tool

  zip:
    executor: default-executor

    steps:
      - *attach-workspace

      - run: |
          npm run build
          npm run package

      - store_artifacts:
          path: ~/repo/pkg

      - *persist-workspace

  test:
    executor: default-executor

    steps:
      - *attach-workspace

      - run: npm test

  security-audit:
    executor: default-executor

    steps:
      - *attach-workspace

      - run: npm run security:audit

  build-u20:
    working_directory: ~/repo
    shell: /bin/bash -eo pipefail
    docker:
      - image: zimbra/zm-base-os:devcore-ubuntu-20.04
    steps:
      - package-builder

  build-u18:
    working_directory: ~/repo
    shell: /bin/bash -eo pipefail
    docker:
      - image: zimbra/zm-base-os:devcore-ubuntu-18.04
    steps:
      - package-builder

  build-u16:
    working_directory: ~/repo
    shell: /bin/bash -eo pipefail
    docker:
      - image: zimbra/zm-base-os:devcore-ubuntu-16.04
    steps:
      - package-builder

  build-c8:
    working_directory: ~/repo
    shell: /bin/bash -eo pipefail
    docker:
      - image: zimbra/zm-base-os:devcore-centos-8
    steps:
      - package-builder

  build-c7:
    working_directory: ~/repo
    shell: /bin/bash -eo pipefail
    docker:
      - image: zimbra/zm-base-os:devcore-centos-7
    steps:
      - package-builder

  deploy-s3:
    working_directory: ~/repo
    docker:
      - image: "cimg/python:2.7"
    steps:
      - *attach-workspace

      - aws-s3/sync:
          from: "~/repo/build/dist/"
          to: "s3://files.zimbra.com/dev-releases/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM/archives/"
          aws-access-key-id: RELEASE_AWS_ACCESS_KEY_ID
          aws-secret-access-key: RELEASE_AWS_SECRET_ACCESS_KEY
          aws-region: RELEASE_AWS_DEFAULT_REGION
          arguments: --acl public-read


################################################

################# Executors ####################

executors:
  default-executor:
    working_directory: ~/repo
    docker:
      - image: cimg/node:14.18

################################################


################# Workflows ####################

workflows:
  version: 2

  commit-workflow:
    jobs:
      - build:
         type: approval

      - prepare-npm-deps:
         requires:
           - build
      - zip:
          requires:
            - prepare-npm-deps

      - test:
          requires:
            - prepare-npm-deps

      - security-audit:
          requires:
            - prepare-npm-deps

      - build-u20:
          requires:
            - zip

      - build-u18:
          requires:
            - zip

      - build-u16:
          requires:
            - zip

      - build-c8:
          requires:
            - zip

      - build-c7:
          requires:
            - zip

      - deploy-s3-approval:
          type: approval
          requires:
            - build-u20
            - build-u18
            - build-u16
            - build-c8
            - build-c7

      - deploy-s3:
          context:
            - aws
          requires:
            - deploy-s3-approval

################################################
